### ISSUE TITLE
Error on C code

### ISSUE THREAD

**Issue by vbextreme** [sunfishcode/hello-world-vs-io-errors#10]
Your test in C Is buggy.
Types 
```
$ man 3 puts
```
And reads return value.
puts return EOF on error, you can try to read returned value and check.
```
if( puts("hello world") == EOF ){
  fprintf(stderr,"%m\n");
}
```
Afters this you can check if you have bug in C.
Is not a bug if you not check a errors.

**Comment by sunfishcode** [comment]
When stdout is redirected to a file, it is typically fully buffered. In that mode, `puts` usually does not perform any I/O; it just writes to a buffer. Consequently, checking the return value of `puts` is not sufficient to detect I/O errors.

I put your proposed code in a complete C program:
```c
#include <stdio.h>

int main(void) {
    if( puts("hello world") == EOF ){
        fprintf(stderr,"%m\n");
    }
    return 0;
}
```

I got this behavior with it:

```c
$ cc t.c
$ ./a.out > /dev/full
$ echo $?
0
```

This indicates that your proposed alternative is not correct.

**Comment by vbextreme** [comment]
The World is complex.
You use a intrinsic features of OS and runtime C.
Runtime C bufferizzed FILE, stdout, and automatic flush and close at exit.
When use automatic garbage you accept default behavior.
puts, fflush, and close manually for gets all errors.
So, if you use valgrind you can see you have file not closed at exit, its not a problems if you want, otherwise, if you want to find a real bug you Need to works manually every time.

Yes it's so hard, yes not all developer works in this mode buts this is another type of problem, and be different to bug.

**Comment by vbextreme** [comment]
```
int main(){
  errno=0;
  puts("hello world");
  fflush(stdout);
  fclose(stdout);
  fprintf(stderr,"%m\n");
  return errno;
}
```
might have some chance of success without flooding our code with ifs

**Comment by sunfishcode** [comment]
That program may work on some platforms, but the C standard in 7.5p3 says "The value of errno may be set to nonzero by a library function call whether or not there is an error, provided the use of errno is not documented in the description of the function in this document." It doesn't document errno values for fprintf, so as far as the standard is concerned, that program could report spurious failures.

**Comment by vbextreme** [comment]
Its only a simplex examples, you can add all you if you want. Is Better.

**Comment by vbextreme** [comment]
the discussion was whether it was a bug, but now we can write:
myth busted

**Comment by sunfishcode** [comment]
I unfortunately don't understand. If you believe there is something that could be improved anywhere in this repository, please say the place and explain it.

**Comment by vbextreme** [comment]
sorry but English in not may native language.
This is not a bug.
I'm going here from you blog, in your article exit from software without check an error.
If you write:
```
int main(){
  int fd = open("~....~", O_WRONLY, 666);
  write(fd, "hello world", 123456789);
  return EXIT_SUCCESS;
}
```
you not have any errors printed on your shell.
Is not a bug, in C you decide what is error and what is not.
as I wrote in my first message, it's not C that's buggy but your code.
your blogs is misleading.

**Comment by sunfishcode** [comment]
The blog post and this repository are about the hello world programs that are presented to newcomers. I agree that it is possible to write a hello world program in C that reports errors. This repository even contains an example of how to do it. But in practice, the hello world programs actually presented to teach people C do not do this.

**Comment by vbextreme** [comment]
I understand what you mean, but in any case it is not a bug.
Exists many software which no report errors and aren't bugs, they just don't see fit.
I thinks Is better change the click bait titles of the blogs, do it as a personal favor, there are many people who keep asking me why it's a bug.

**Comment by sunfishcode** [comment]
I do consider it to be a bug. Error reporting shouldn't be something one does when one sees fit. It should be the default.

**Comment by vbextreme** [comment]
In C you need to manual check the errors, nothing happens magically in C.
If you not check is your problems not a language problems.

**Comment by sunfishcode** [comment]
Regardless of whose problem it is, if the end result is that error reporting is left out of the hello world presented to newcomers, I consider it to be a bug in that hello world.

**Comment by vbextreme** [comment]
So on Linux if you use optimistic memory allocation and malloc not return errors if you end of memory is a bug for you?

**Comment by sunfishcode** [comment]
By optimistic memory allocation, do you mean [overcommit](https://www.kernel.org/doc/Documentation/vm/overcommit-accounting)? Then no, that's not necessarily a bug. If the OOM killer kills a process, It does get reported to the parent process.

Or, do you mean calling `malloc` and not checking for errors? Then yes, that's a bug. `malloc` can return NULL, and dereferencing a NULL pointer produces undefined behavior.

**Comment by vbextreme** [comment]
Yes, overcommit.
If you have device with 1GiB of memory and call malloc with 10GiB of size not return errors(x64), but you not have real memory.
OOM killer it could intervene much later in the code, not after malloc.
And OOM can kill you or others process, not give an error with which you can decide what to do.
So, if you call
```
char* mem=malloc(1024UL*1024UL*1024UL*10);
```
You can't check if you have Memory or not, can only wait OOM kill you or others process, if you have OOM killer.

So Is this a bug? when i reading writing solid code book , I think understood that it would be better never to return error(in real world Is to be impossible).
From this principle and from the fact that the hello world example exercises have to write on video, I believe that not handling errors is not a bug but the right way to handle errors.

**Comment by sunfishcode** [comment]
The key question is: does the parent process learn what happened?

If a child process doesn't check for errors after calling `printf`, and an error occurs, the parent process does not get notified. Nobody gets notified. The error is silently dropped, and the parent may assume that the child completed its task successfully, when in fact it has failed.

If a child process does `mallloc(1028UL*1024UL*1024UL*10)` and later gets killed by the OOM killer, then the parent process *does* get notified. The parent will see `WIFEXITED` return false and `WIFSIGNALED` return true, so it will know that the child process did not complete its task successfully.

**Comment by vbextreme** [comment]
it is the callee who decides which errors to throw, not the caller who decides what they should be.
I think it is more Dangerous to handle an error that the callee has decided to ignore.
In your special examples, where have a parent process and OOM killer, the child process Is unable to stop execution without reporting errors, only child process know if Is error or not. In this situations probably you need to add a rules on OOM killer.

But return on threads.
Creating more complex hello world, writing "hello" and "world" in two Lines
Probably you write:
```
int puts_safe(const char* str){
  if( puts(str) || fflush(stdout) || ferro(stdout) ) return -1;
}

int main(){
  if( puts_safe("hello") ) return errno;
  if( puts_safe("world") ) return errno;
  return 0;
}
```
You correct return error value but you have destroy usefull buffer.

Need to thinks the problem: writing hello and world in video.

Now we need to thinks if stdout can return error on writing on the video and if an error occurs, can I display it to the user?
After this search probably you write:
```
int main(){
  puts("hello");
  puts("world");
  return 0;
}
```
Or more expressive code

```
void writing_hello_world_in_two_line_on_video(void){
  puts("hello");
  puts("world");
}

int main(){
  writing_hello_world_in_two_line_on_video();
  return 0;
}
```

Now if the user redirect the stdout Is improper use of the software.
So you can call dd software and destroy any part of your fs but dd not tell you that improper use of software.

**Comment by sunfishcode** [comment]
> only child process know if Is error or not.

I disagree with this. The default expectation of any software is that an OOM kill event is an error.

> Now if the user redirect the stdout Is improper use of the software.

The default expectation of any software that writes to stdout is that the user may redirect the output to a file.

> So you can call dd software and destroy any part of your fs but dd not tell you that improper use of software.

If I don't expect dd to destroy my fs, and I run it, and it does destroy my fs, it is not a bug in *dd*. `dd` did exactly what it was asked to do. One could reasonably argue that it's a bug in Unix, as a whole, for having such dangerous commands. Or perhaps it's a bug in the decision to use Unix in a particular situation. But it's not a bug in `dd` itself.

**Comment by vbextreme** [comment]
> I disagree with this. The default expectation of any software is that an OOM kill event is an error.

the fact that you have to configure OOM killer to handle all the special cases should put you in doubt.
OOM killer it doesn't know the state of the process and it doesn't even know if running out of memory might be a big mistake or not, you need to explain it to it otherwise you might end up with the initd killed.
OOM killer is nothing more than a workaround to try and keep your nice server/desktop alive, far from proper error handling, this Is a good services but not realy good error handle.
Try to thinks this:
```
size_t fill_the_bar(char* bar, size_t size);
void do_the_bar(char* bar, size_t size);

void foo(){
  char* bar = malloc(N);
  if( !bar ){
    errno = 0;
    size_t n = 0;
    char buf[4096];
    while( n < N ){
      size_t nb = fill_the_bar(bar,  4096);
      do_the_bar(bar, nb);
      n+=nb;
    }
  }
  else{
    size_t n = 0;
    while( n < N ){
      size_t nb = fill_the_bar(bar,  N);
      do_the_bar(bar, nb);
      n+=nb;
    }
  }
}
```
Oom killer can kill process and raise error to parent.
But child can run with ENOMEM error, and in this case decide to erase error and continue run the software.
Only a child know the real state and if you can running.
OOM killer Is not a Memory Manager error, manager Who kill without compromise your system.
Only solutions Is only to disabile overcommit, but you'd be willing to lose any overcommit benefit just to have an useless ENOMEM ?

> The default expectation of any software that writes to stdout is that the user may redirect the output to a file.

I don't remember if the k&r specifies which operating system you have to run hello world on.
But why you assuming that you have a complete operating system underneath with a shell attached?
Maybe whoever wrote hello world assumed you were using an avr328p.

> dd did exactly what it was asked to do.

same examples hello world, write hello world in your terminal.

**Comment by sunfishcode** [comment]
One can certainly question Linux's design choices that lead it to have an OOM killer. Can it cause data loss? Yes. Can it kill things that might have otherwise been able to recover? Yes.

But, do *applications* have a bug if the OOM killer kills them? No. The parent is notified, and it knows that the process was killed rather than exiting normally, so it at least knows the child did not succeed in its task.

You can argue that the OOM killer itself is a bug. But if so, it's a bug in the design of Linux. It's not a bug in individual applications.

> I don't remember if the k&r specifies which operating system you have to run hello world on. But why you assuming that you have a complete operating system underneath with a shell attached? Maybe whoever wrote hello world assumed you were using an avr328p.

This is why I said "default expectation". The hello world you'll find in C tutorials doesn't say "this assumes it's on an avr328p".

> > dd did exactly what it was asked to do.
> 
> same examples hello world, write hello world in your terminal.

The default expectation of any software that writes to stdout is that the user may redirect the output to a file. If that fails, for any reason, then hello world did not do what it was asked to do, and it should notify its parent that it failed.

**Comment by vbextreme** [comment]
> But, do applications have a bug if the OOM killer kills them? No.

False, yes applications have a bug, because not have error on malloc. This is crucial to understand.
For examples your server execute my code, OOM kill my process but process is very important for the server itself, then run it again and OOM does it again. The application may never run even though the software code itself is "bug free".
Linux behaves like this for an optimization, the developers will surely have wondered: "is better a fast software that doesn't have a direct control on malloc or slow software but has malloc error checking?"
Surely more speed is better, others may think a error is better. But the truth is, the less mistakes you make, the less mistakes the programmer can make.
Try looking:
```
char* wow = malloc(N);
*wow = 0;
```
This code have a bug, not check error on malloc, but now try to calculate the probability that that code will break with overcommit and without.
without overcommit that code will eventually break.
With overcommit you have less probably, very less probably, at most OOM killer will kill him.
Not return errors is always a best choise, in this case Is more fast and more safe.

Can apply same to hello world, in my previous snippets safe version of puts, broken buffered output because every time you need to clean buffer for checking all errors, buffered mode would become useless.
You then have to make a choice, performance or unnecessary error checking.
Having to explain this to a novice programmer on the first example in the book seems somewhat complicated to me.
So, it's not a bug, the authors prefer performance and simplicity to introduce the language.

> This is why I said "default expectation". The hello world you'll find in C tutorials doesn't say "this assumes it's on an avr328p".

It doesn't even assume it's running on Linux or other os. Nor that it's run in a shell or that they have the ability to redirect output.
It's generic code that does exactly what it wants to do on any machine that can compile C or a dialect of it.

> The default expectation of any software that writes to stdout is that the user may redirect the output to a file. If that fails, for any reason, then hello world did not do what it was asked to do, and it should notify its parent that it failed.

Where can I find it, written in output can be redirected to any file? Can you point me to the man page?
Where can I find that the child need always to return error to parent if have an error? Can you point me to the man page?

I have open the K&R, in original language "print output" and book translate in my native lang types "this show", so the code need show "hello world".
We can therefore deduce that everything else is undefined behavior.
The software doesn't have to do what you want, but what it was made to do.
In this case it does exactly what it says in the book, if you redirect it the behavior is undefined because the developer not have tell you if is a bug or a features.

**Comment by sunfishcode** [comment]
Unfortunately, I perceive we've reached the point where it doesn't seem productive to continue.

**Comment by vbextreme** [comment]
I also think we should take a break to think about it better.
out of curiosity I wanted to ask chatgpt what he thought, and it seems that it was considered a bug but it depends on the context as I was saying.


> Generally, if the software is unable to write to a specific file, it could be considered a bug. In this case, it may be appropriate to return a different exit value than EXIT_SUCCESS to indicate that the program did not complete successfully. Furthermore, it may be useful to handle the error and notify the user or log the error to facilitate debugging and problem resolution. However, it depends on the logic of your program and your specifications. If your program has other tasks that have been completed correctly, and the file writing error is a marginal case, then it may be justifiable to return EXIT_SUCCESS. In any case, it would be important to handle the error and notify the user or log the error.

**Comment by sunfishcode** [comment]
To be sure, chatgpt is not any kind of authority. But also, summarizing text that includes the words "In any case, it would be important to handle the error and notify the user or log the error" with just "but it depends on the context" is revealing.

I stand by the blog post. I hope that the additional explanations I've given here are helpful.
