### ISSUE TITLE
Maybe also show some fixes to the hello world bug?

### ISSUE THREAD

**Issue by thebesttv** [sunfishcode/hello-world-vs-io-errors#5]
I understand that the intention is to "test the programs that are presented to newcomers and not programs specifically written to fix this bug".  But instead of just saying the hello world tutorial code is bugged, would it be mote helpful to also show some fixes (or links to fixes) to the bug?

**Comment by sunfishcode** [comment]
Yes, this was mentioned in various places in the online comments too. I've now opened #6 to add an Examples.md page which can collect such examples.
